config {
    type: "assertion",
    schema: dataform.projectConfig.vars.QUALITY_DATASET,
    disabled: false,
    description: "Ensures that user_pseudo_id is not NULL in GA4 events.",
    dependencies: [{name: "ga4_events"}],
    tags: [dataform.projectConfig.vars.GA4_DATASET, "assertions"]
}

SELECT
  event_id
FROM
  ${ref("ga4_events")}
WHERE
  event_date >= DATE_SUB(CURRENT_DATE(), INTERVAL 3 DAY)
  AND user_pseudo_id IS NULL
